language: python

python:
  - "2.7"

services:
  - redis-server

install:
  - "pip install --upgrade setuptools"
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"

script:
  - "py.test"

services:
  - redis-server

after_success:
  - "coveralls"

notifications:
  email: false

sudo: false

